/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pets.telasMob;

//import pets.telas.CadastroAnimal;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pets.persistenciaArquivo.PersistenciaArquivo;
import pets.telas.Principal;


/**
 *
 * @author Maiky
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        botaoMenu = new javax.swing.JButton();
        botaoPontos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoRede = new javax.swing.JButton();
        botaoPets = new javax.swing.JButton();
        mapa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botaoAdicionar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botaoEditar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botaoEditar1 = new javax.swing.JButton();
        botaoEditar3 = new javax.swing.JButton();
        botaoEditar4 = new javax.swing.JButton();
        botaoEditar5 = new javax.swing.JButton();
        botaoEditar6 = new javax.swing.JButton();
        botaoEditar2 = new javax.swing.JButton();
        botaoEditar7 = new javax.swing.JButton();
        botaoEditar8 = new javax.swing.JButton();
        botaoEditar9 = new javax.swing.JButton();
        botaoEditar10 = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(300, 533));
        setMinimumSize(new java.awt.Dimension(300, 533));
        setPreferredSize(new java.awt.Dimension(300, 533));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\logo2.png")); // NOI18N

        botaoMenu.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\menu2.png")); // NOI18N
        botaoMenu.setToolTipText("Menu");
        botaoMenu.setBorder(null);
        botaoMenu.setContentAreaFilled(false);
        botaoMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });

        botaoPontos.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\3pontos2.png")); // NOI18N
        botaoPontos.setToolTipText("Sair da conta");
        botaoPontos.setBorderPainted(false);
        botaoPontos.setContentAreaFilled(false);
        botaoPontos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPontos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPontosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addComponent(botaoPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoPontos))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(242, 167, 30));

        botaoRede.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        botaoRede.setForeground(new java.awt.Color(255, 255, 255));
        botaoRede.setText("REDE");
        botaoRede.setBorderPainted(false);
        botaoRede.setContentAreaFilled(false);
        botaoRede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botaoPets.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        botaoPets.setForeground(new java.awt.Color(255, 255, 255));
        botaoPets.setText("PETS");
        botaoPets.setBorderPainted(false);
        botaoPets.setContentAreaFilled(false);
        botaoPets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoRede)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(botaoPets)
                    .addContainerGap(178, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoRede, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(botaoPets, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        mapa.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\mapa.png")); // NOI18N
        mapa.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        botaoAdicionar.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\adicionarTrans.png")); // NOI18N
        botaoAdicionar.setToolTipText("Adicionar um animal");
        botaoAdicionar.setBorderPainted(false);
        botaoAdicionar.setContentAreaFilled(false);
        botaoAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");
        jPanel4.setAlignmentY(0.0F);

        botaoEditar.setFont(new java.awt.Font("Khmer UI", 1, 10)); // NOI18N
        botaoEditar.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar.setText("Editar");
        botaoEditar.setBorder(null);
        botaoEditar.setBorderPainted(false);
        botaoEditar.setContentAreaFilled(false);
        botaoEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\IFES\\4 semestre\\POO1\\fundo.png")); // NOI18N

        botaoEditar1.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar1.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar1.setText("Nome:");
        botaoEditar1.setBorder(null);
        botaoEditar1.setBorderPainted(false);
        botaoEditar1.setContentAreaFilled(false);
        botaoEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar1ActionPerformed(evt);
            }
        });

        botaoEditar3.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar3.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar3.setText("Tipo:");
        botaoEditar3.setBorder(null);
        botaoEditar3.setBorderPainted(false);
        botaoEditar3.setContentAreaFilled(false);
        botaoEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar3ActionPerformed(evt);
            }
        });

        botaoEditar4.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar4.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar4.setText("Cor:");
        botaoEditar4.setBorder(null);
        botaoEditar4.setBorderPainted(false);
        botaoEditar4.setContentAreaFilled(false);
        botaoEditar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar4ActionPerformed(evt);
            }
        });

        botaoEditar5.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar5.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar5.setText("Raça:");
        botaoEditar5.setBorder(null);
        botaoEditar5.setBorderPainted(false);
        botaoEditar5.setContentAreaFilled(false);
        botaoEditar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar5ActionPerformed(evt);
            }
        });

        botaoEditar6.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar6.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar6.setText("Porte:");
        botaoEditar6.setBorder(null);
        botaoEditar6.setBorderPainted(false);
        botaoEditar6.setContentAreaFilled(false);
        botaoEditar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar6ActionPerformed(evt);
            }
        });

        botaoEditar2.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar2.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar2.setText("?");
        botaoEditar2.setBorder(null);
        botaoEditar2.setBorderPainted(false);
        botaoEditar2.setContentAreaFilled(false);
        botaoEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar2ActionPerformed(evt);
            }
        });

        botaoEditar7.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar7.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar7.setText("?");
        botaoEditar7.setBorder(null);
        botaoEditar7.setBorderPainted(false);
        botaoEditar7.setContentAreaFilled(false);
        botaoEditar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar7ActionPerformed(evt);
            }
        });

        botaoEditar8.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar8.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar8.setText("?");
        botaoEditar8.setBorder(null);
        botaoEditar8.setBorderPainted(false);
        botaoEditar8.setContentAreaFilled(false);
        botaoEditar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar8ActionPerformed(evt);
            }
        });

        botaoEditar9.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar9.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar9.setText("?");
        botaoEditar9.setBorder(null);
        botaoEditar9.setBorderPainted(false);
        botaoEditar9.setContentAreaFilled(false);
        botaoEditar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar9ActionPerformed(evt);
            }
        });

        botaoEditar10.setFont(new java.awt.Font("Khmer UI", 1, 12)); // NOI18N
        botaoEditar10.setForeground(new java.awt.Color(153, 153, 153));
        botaoEditar10.setText("?");
        botaoEditar10.setBorder(null);
        botaoEditar10.setBorderPainted(false);
        botaoEditar10.setContentAreaFilled(false);
        botaoEditar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditar10ActionPerformed(evt);
            }
        });

        botaoDeletar.setFont(new java.awt.Font("Khmer UI", 1, 10)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(153, 153, 153));
        botaoDeletar.setText("Deletar");
        botaoDeletar.setBorder(null);
        botaoDeletar.setBorderPainted(false);
        botaoDeletar.setContentAreaFilled(false);
        botaoDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(78, 78, 78))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoEditar4)
                            .addComponent(botaoEditar5)
                            .addComponent(botaoEditar6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoEditar1)
                            .addComponent(botaoEditar3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoEditar7)
                            .addComponent(botaoEditar8)
                            .addComponent(botaoEditar9)
                            .addComponent(botaoEditar10))
                        .addGap(73, 73, 73))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(botaoEditar2)
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addComponent(botaoDeletar)
                        .addGap(11, 11, 11)
                        .addComponent(botaoEditar)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoEditar2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(botaoEditar7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(botaoEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar6))))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditar)
                    .addComponent(botaoDeletar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
        CadastroAnimal cadastroAnimal = new CadastroAnimal();
        cadastroAnimal.setVisible(true);
        this.hide();
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar3ActionPerformed

    private void botaoEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar1ActionPerformed

    private void botaoEditar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar4ActionPerformed

    private void botaoEditar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar5ActionPerformed

    private void botaoEditar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar6ActionPerformed

    private void botaoEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar2ActionPerformed

    private void botaoEditar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar7ActionPerformed

    private void botaoEditar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar8ActionPerformed

    private void botaoEditar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar9ActionPerformed

    private void botaoEditar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditar10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditar10ActionPerformed

    private void botaoPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPetsActionPerformed

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        Menu menu;
        try {
            menu = new Menu();
            menu.setVisible(true);
            this.hide();
        } catch (IOException ex) {
            Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoMenuActionPerformed

    private void botaoPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPontosActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoPontosActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        String nome = JOptionPane.showInputDialog("Nome do animal");
        PersistenciaArquivo deletar = new PersistenciaArquivo();
        try {
            deletar.deletarDadosAnimal(nome,"animal.csv"); //Deletar animal do parâmetro nome
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoEditar1;
    private javax.swing.JButton botaoEditar10;
    private javax.swing.JButton botaoEditar2;
    private javax.swing.JButton botaoEditar3;
    private javax.swing.JButton botaoEditar4;
    private javax.swing.JButton botaoEditar5;
    private javax.swing.JButton botaoEditar6;
    private javax.swing.JButton botaoEditar7;
    private javax.swing.JButton botaoEditar8;
    private javax.swing.JButton botaoEditar9;
    private javax.swing.JButton botaoMenu;
    private javax.swing.JButton botaoPets;
    private javax.swing.JButton botaoPontos;
    private javax.swing.JButton botaoRede;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mapa;
    // End of variables declaration//GEN-END:variables
}
